### ISSUE TITLE
Question about using ROSJAVA with existing ros network

### ISSUE THREAD

**Issue by ssh10032** [SpyrosKou/Plain-ROS-Java-System-Example#2]
Thank you for providing a good code!

Since ros noetic is not supported by rosjava, **I would like to implement communication with the rospy nodes of the existing ros noetic communication using the ROSJAVA code you provided.** 

**May I know if your ROSJAVA can be used in parallel with the existing ros network?**

Once again, thank you for providing a good and useful code!

**Comment by SpyrosKou** [comment]
Hi @ssh10032 ,
Its my pleasure to know that you find this example useful. 
Do you mean that you will have roscore started in noetic?

If yes, then yes these examples will also work in noetic. 
I added an example on how to run the rosjava example code with an external `roscore` [MainExternal](https://github.com/SpyrosKou/Plain-ROS-Java-System-Example/blob/main/src/main/java/eu.spyros.koukas.ros.examples/MainExternal.java).

I also added some info in the [readme](https://github.com/SpyrosKou/Plain-ROS-Java-System-Example/blob/main/README.md)

Let me know if you need more details.

**Comment by ssh10032** [comment]
Thank you for your guidance of kind reply and adding the code!!

I confirmed that the communication is wroking well through external roscore with the code you added.

For continuous ros communication, I would like to block the last part of the code and use it.
`//System.exit(EXIT_OK);`
Is there any problem in blocking it?

And how can I subscribe custom msg in ROSJAVA?

Thank you again for your help.

**Comment by SpyrosKou** [comment]
You are welcome, I am glad it helps. 

Thank you for confirming that it works OK.

> For continuous ros communication, I would like to block the last part of the code and use it.
> `//System.exit(EXIT_OK);`
> Is there any problem in blocking it?

You can change the code to work continuously in your application. The functionality of rosjava does not require exiting the code.
The current example purposely ends after some time, as it is only a demo.

To subscribe to a custom msg in ROSJAVA you need to create custom rosjava message descriptions and add them as a dependency in your project.

**Comment by SpyrosKou** [comment]
@ssh10032 In case it helps, I have created this [Custom-Messages-ROS-Java-System-Example](https://github.com/SpyrosKou/Custom-Messages-ROS-Java-System-Example) that shows how to create the required ROS artifacts from custom ROS message definitions.

**Comment by SpyrosKou** [comment]
Closing the issue as there is no action pending.
