### ISSUE TITLE
Custom android project merging with Plain-ROS-Java-System-Example

### ISSUE THREAD

**Issue by PercivalChan** [SpyrosKou/Plain-ROS-Java-System-Example#4]
Dear SpyrosKou,

  Greetings! First of all, thank you for you clean and straight forward example. I am a student that completely new to ROS. I am currently working on a personal android-ROS communication project. However, the version problem annoyed me for a whole month, your project gave me the direction of ROS functions. I am sorry if I ask stupid question, how can I make the functions work if I want to communicate with ROS through android? (Like the app "ROSandroid") I would like to receive map data from ROS robot that my friend working on and visualize it on the phone. May you kindly point me some directions? As this project is the most updated source that I can find through out these two months. I know this is not an project issue but I will keep learning and any guidance are welcome! Thank you so much for you time and the example project!

Best
Percival

**Comment by SpyrosKou** [comment]
Dear @PercivalChan thank you for your kind words.
It is a pleasure to know that this project helped you. 

Well when it comes to visualization in Android you have many options.
Indicatively:

-  ROS Java to subscribe to a ROS topic publishing the map data.
If you use this approach, you can add rosjava as a dependency in your Android project and use it in a way similar to the provided examples.

- (Rosbridge)[http://wiki.ros.org/rosbridge_suite] to make data available as (websockets)[https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API] and consume them with other technologies. E.g. (React Native)[https://reactnative.dev/] 


It all depends on the technologies that will be used and the overall requirements of the project.

Perhaps more help could be found on resources and forums for ROS Java and Android.

Best regards,
Spyros

**Comment by SpyrosKou** [comment]
Closing this issue as there is no further action to be taken.
